server:
  port: 8003

spring:
  application:
    name: springcloud-provider-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/payment?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    druid:
      test-while-idle: true
      validation-query: SELECT 1
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181